name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd function-app
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          pytest function-app/tests/ --cov=function-app --cov-report=xml